# Generated by Django 5.1.3 on 2024-11-30 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_avatar_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 27, 18, 943935)),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 27, 18, 943676)),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 27, 18, 943373)),
        ),
    ]
