# Generated by Django 5.1.3 on 2024-11-30 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_upload_time_post_upload_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_date',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648814)),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648430)),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648044)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648801)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648415)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 29, 37, 648016)),
        ),
    ]
