# Generated by Django 5.1.3 on 2024-11-30 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment_upload_date_post_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.TimeField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 30, 2, 957540)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.TimeField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 30, 2, 957273)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.TimeField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 30, 2, 957002)),
        ),
    ]
