# Generated by Django 5.1.3 on 2024-11-30 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comment_upload_time_alter_post_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 32, 34, 29154)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 32, 34, 28756)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 32, 34, 28355)),
        ),
    ]
