# Generated by Django 5.1.3 on 2024-11-30 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_comment_upload_time_alter_post_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 6, 23, 444427)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 6, 23, 444143)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 6, 23, 443819)),
        ),
    ]
