# Generated by Django 5.1.3 on 2024-12-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_comment_upload_time_alter_post_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 6)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 12, 6, 17, 52, 37, 19869)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 6)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 12, 6, 17, 52, 37, 19592)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 6)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 12, 6, 17, 52, 37, 19287)),
        ),
    ]
